// AUTO-GENERATED by scripts/fetch-pioneers-media.mjs
// Contextual images per pioneer, interleaved into the biography.
// `after` is the 0-based paragraph index the image appears after.

export type PioneerMediaItem = {
  src: string;
  caption: string;
  after: number;
};

export const PIONEER_MEDIA: Record<string, PioneerMediaItem[]> = {
  "lucretius": [
    { src: "/images/pioneers/lucretius-work.jpg", caption: "De rerum natura, his epic poem on the nature of things.", after: 2 },
    { src: "/images/pioneers/lucretius-g1.jpg", caption: "Epicurus, the Greek philosopher whose teaching Lucretius followed.", after: 1 },
    { src: "/images/pioneers/lucretius-g2.jpg", caption: "Democritus, an early Greek atomist whose ideas echo through the poem.", after: 3 },
  ],
  "vitruvius": [
    { src: "/images/pioneers/vitruvius-work.jpg", caption: "De architectura, the oldest surviving treatise on building.", after: 2 },
    { src: "/images/pioneers/vitruvius-g1.jpg", caption: "The Maison Carrée, a Roman temple of the kind Vitruvius described.", after: 2 },
    { src: "/images/pioneers/vitruvius-g2.jpg", caption: "Leonardo's Vitruvian Man, drawn from Vitruvius' note on human proportion.", after: 4 },
  ],
  "pliny-the-elder": [
    { src: "/images/pioneers/pliny-the-elder-work.jpg", caption: "Naturalis Historia, his vast encyclopaedia of the natural world.", after: 2 },
    { src: "/images/pioneers/pliny-the-elder-g1.jpg", caption: "The eruption of Vesuvius in 79 AD, which he sailed toward and did not survive.", after: 4 },
  ],
  "frontinus": [
    { src: "/images/pioneers/frontinus-work.jpg", caption: "A Roman aqueduct, the engineering he documented and managed.", after: 2 },
    { src: "/images/pioneers/frontinus-g1.jpg", caption: "The Pont du Gard, a surviving Roman aqueduct bridge in Gaul.", after: 3 },
  ],
  "guido-of-arezzo": [
    { src: "/images/pioneers/guido-of-arezzo-work.jpg", caption: "The Guidonian hand, his memory aid for singing the scale.", after: 3 },
    { src: "/images/pioneers/guido-of-arezzo-g1.jpg", caption: "A chant manuscript with the staff notation his system made possible.", after: 2 },
  ],
  "fibonacci": [
    { src: "/images/pioneers/fibonacci-work.png", caption: "The Fibonacci sequence, where each number is the sum of the two before.", after: 3 },
    { src: "/images/pioneers/fibonacci-g1.jpg", caption: "Liber Abaci, the book that brought Arabic numerals to Europe.", after: 2 },
    { src: "/images/pioneers/fibonacci-g2.png", caption: "The golden ratio, closely tied to the Fibonacci numbers.", after: 4 },
  ],
  "marco-polo": [
    { src: "/images/pioneers/marco-polo-work.jpg", caption: "The Travels of Marco Polo, his account of the journey east.", after: 3 },
    { src: "/images/pioneers/marco-polo-g1.jpg", caption: "Kublai Khan, the Mongol emperor at whose court Polo served.", after: 2 },
    { src: "/images/pioneers/marco-polo-g2.png", caption: "The Silk Road, the trade routes he travelled to reach China.", after: 1 },
  ],
  "filippo-brunelleschi": [
    { src: "/images/pioneers/filippo-brunelleschi-work.jpg", caption: "The dome of Florence Cathedral, raised without external scaffolding.", after: 2 },
    { src: "/images/pioneers/filippo-brunelleschi-g1.jpg", caption: "The Baptistery doors, whose competition launched his career.", after: 1 },
    { src: "/images/pioneers/filippo-brunelleschi-g2.png", caption: "Masaccio's Holy Trinity, an early triumph of the linear perspective he devised.", after: 4 },
  ],
  "donatello": [
    { src: "/images/pioneers/donatello-work.jpg", caption: "The equestrian statue of Gattamelata, the first of its kind since antiquity.", after: 3 },
    { src: "/images/pioneers/donatello-g1.jpg", caption: "Judith and Holofernes, his dramatic late bronze.", after: 2 },
  ],
  "luca-pacioli": [
    { src: "/images/pioneers/luca-pacioli-work.jpg", caption: "Summa de arithmetica, his great compendium of mathematics.", after: 2 },
    { src: "/images/pioneers/luca-pacioli-g2.png", caption: "Divina proportione, illustrated by his friend Leonardo da Vinci.", after: 4 },
  ],
  "christopher-columbus": [
    { src: "/images/pioneers/christopher-columbus-work.png", caption: "A map of the voyages that opened the Atlantic crossing.", after: 3 },
    { src: "/images/pioneers/christopher-columbus-g1.jpg", caption: "The Santa María, the flagship of his first voyage in 1492.", after: 2 },
  ],
  "leonardo-da-vinci": [
    { src: "/images/pioneers/leonardo-da-vinci-g1.jpg", caption: "The Mona Lisa, the most famous painting in the world.", after: 2 },
    { src: "/images/pioneers/leonardo-da-vinci-g2.jpg", caption: "The Last Supper, his mural in Milan.", after: 2 },
    { src: "/images/pioneers/leonardo-da-vinci-work.jpg", caption: "The Vitruvian Man, his study of human proportion.", after: 4 },
  ],
  "amerigo-vespucci": [
    { src: "/images/pioneers/amerigo-vespucci-work.jpg", caption: "Vespucci realised the new lands were a separate continent.", after: 2 },
    { src: "/images/pioneers/amerigo-vespucci-g1.jpg", caption: "The 1507 Waldseemüller map, the first to label the land 'America'.", after: 4 },
  ],
  "michelangelo": [
    { src: "/images/pioneers/michelangelo-work.jpg", caption: "David, carved from a single flawed block of marble.", after: 2 },
    { src: "/images/pioneers/michelangelo-g1.jpg", caption: "The Sistine Chapel ceiling, painted over four years on his back.", after: 3 },
    { src: "/images/pioneers/michelangelo-g2.jpg", caption: "The Pietà, finished when he was just twenty-four.", after: 2 },
  ],
  "raphael": [
    { src: "/images/pioneers/raphael-work.jpg", caption: "The School of Athens, his fresco of the great ancient thinkers.", after: 3 },
    { src: "/images/pioneers/raphael-g1.jpg", caption: "The Sistine Madonna, among his most beloved works.", after: 2 },
  ],
  "gerolamo-cardano": [
    { src: "/images/pioneers/gerolamo-cardano-work.gif", caption: "The gimbal, a self-levelling suspension named after him.", after: 3 },
    { src: "/images/pioneers/gerolamo-cardano-g1.jpg", caption: "Tartaglia, his rival in the famous duel over cubic equations.", after: 2 },
  ],
  "andrea-palladio": [
    { src: "/images/pioneers/andrea-palladio-work.jpg", caption: "Villa La Rotonda, his perfectly symmetrical country house.", after: 2 },
    { src: "/images/pioneers/andrea-palladio-g1.jpg", caption: "The Four Books of Architecture, his enduring treatise.", after: 3 },
    { src: "/images/pioneers/andrea-palladio-g2.jpg", caption: "Jefferson's Monticello, one of countless buildings he inspired.", after: 5 },
  ],
  "galileo-galilei": [
    { src: "/images/pioneers/galileo-galilei-work.png", caption: "His study of falling bodies and motion.", after: 2 },
    { src: "/images/pioneers/galileo-galilei-g1.png", caption: "The four moons of Jupiter he discovered through his telescope.", after: 3 },
    { src: "/images/pioneers/galileo-galilei-g2.jpg", caption: "The phases of Venus, proof that it orbits the Sun.", after: 3 },
    { src: "/images/pioneers/galileo-galilei-g3.png", caption: "Galileo before the Inquisition, tried for defending Copernicus.", after: 5 },
  ],
  "caravaggio": [
    { src: "/images/pioneers/caravaggio-work.jpg", caption: "The Calling of Saint Matthew, lit by his dramatic shafts of light.", after: 3 },
    { src: "/images/pioneers/caravaggio-g1.jpg", caption: "Bacchus, from his early years in Rome.", after: 2 },
    { src: "/images/pioneers/caravaggio-g2.jpg", caption: "Judith Beheading Holofernes, raw and violent realism.", after: 3 },
  ],
  "gian-lorenzo-bernini": [
    { src: "/images/pioneers/gian-lorenzo-bernini-work.jpg", caption: "The Ecstasy of Saint Teresa, marble turned to soft flesh and cloth.", after: 3 },
    { src: "/images/pioneers/gian-lorenzo-bernini-g1.jpg", caption: "Apollo and Daphne, sculpted when he was in his twenties.", after: 2 },
    { src: "/images/pioneers/gian-lorenzo-bernini-g2.jpg", caption: "St. Peter's Square, embraced by his sweeping colonnade.", after: 4 },
  ],
  "evangelista-torricelli": [
    { src: "/images/pioneers/evangelista-torricelli-work.jpg", caption: "The barometer, his instrument for measuring air pressure.", after: 3 },
    { src: "/images/pioneers/evangelista-torricelli-g1.jpg", caption: "Galileo, whose assistant Torricelli became at the end of his life.", after: 1 },
  ],
  "giovanni-domenico-cassini": [
    { src: "/images/pioneers/giovanni-domenico-cassini-work.jpg", caption: "Saturn and its rings, which he studied in detail.", after: 2 },
    { src: "/images/pioneers/giovanni-domenico-cassini-g1.jpg", caption: "The Cassini Division, the gap in Saturn's rings he discovered.", after: 3 },
    { src: "/images/pioneers/giovanni-domenico-cassini-g2.jpg", caption: "The Cassini spacecraft, named in his honour centuries later.", after: 5 },
  ],
  "marcello-malpighi": [
    { src: "/images/pioneers/marcello-malpighi-work.png", caption: "Capillaries, the tiny vessels he was first to observe.", after: 3 },
    { src: "/images/pioneers/marcello-malpighi-g1.png", caption: "A 17th-century compound microscope, the kind of instrument that revealed his capillaries.", after: 1 },
  ],
  "antonio-stradivari": [
    { src: "/images/pioneers/antonio-stradivari-work.jpg", caption: "A Stradivarius violin, still unmatched after three centuries.", after: 2 },
    { src: "/images/pioneers/antonio-stradivari-g1.jpg", caption: "The 'Messiah', one of his most celebrated surviving instruments.", after: 3 },
  ],
  "antonio-vivaldi": [
    { src: "/images/pioneers/antonio-vivaldi-work.jpg", caption: "The published score of his Op. 8, the 1725 set that opens with The Four Seasons.", after: 3 },
    { src: "/images/pioneers/antonio-vivaldi-g1.jpg", caption: "The Pietà in Venice, the orphanage where he taught and composed.", after: 2 },
  ],
  "joseph-louis-lagrange": [
    { src: "/images/pioneers/joseph-louis-lagrange-work.jpg", caption: "Mécanique analytique, his sweeping reformulation of mechanics.", after: 3 },
    { src: "/images/pioneers/joseph-louis-lagrange-g1.png", caption: "Lagrange points, the gravitational sweet spots he predicted.", after: 4 },
  ],
  "luigi-galvani": [
    { src: "/images/pioneers/luigi-galvani-work.jpg", caption: "His experiments making frog legs twitch with electricity.", after: 3 },
    { src: "/images/pioneers/luigi-galvani-g1.jpg", caption: "Alessandro Volta, whose challenge to Galvani led to the battery.", after: 4 },
  ],
  "alessandro-volta": [
    { src: "/images/pioneers/alessandro-volta-work.png", caption: "The voltaic pile, the first true electric battery.", after: 3 },
    { src: "/images/pioneers/alessandro-volta-g1.jpg", caption: "The battery, the descendant of his pile that powers the modern world.", after: 4 },
  ],
  "amedeo-avogadro": [
    { src: "/images/pioneers/amedeo-avogadro-work.png", caption: "Avogadro's law on the volume of gases.", after: 3 },
    { src: "/images/pioneers/amedeo-avogadro-g1.jpg", caption: "Cannizzaro, who revived Avogadro's idea after his death.", after: 4 },
  ],
  "antonio-meucci": [
    { src: "/images/pioneers/antonio-meucci-work.jpg", caption: "An early telephone apparatus of the kind he built.", after: 3 },
    { src: "/images/pioneers/antonio-meucci-g1.jpg", caption: "Bell, who patented the telephone amid lasting dispute over priority.", after: 4 },
  ],
  "giuseppe-verdi": [
    { src: "/images/pioneers/giuseppe-verdi-work.jpg", caption: "La traviata, among the most performed operas in the world.", after: 3 },
    { src: "/images/pioneers/giuseppe-verdi-g1.jpg", caption: "Nabucco, the opera that made him a national figure.", after: 1 },
    { src: "/images/pioneers/giuseppe-verdi-g2.jpg", caption: "Aida, his grand opera set in ancient Egypt.", after: 2 },
  ],
  "camillo-golgi": [
    { src: "/images/pioneers/camillo-golgi-work.png", caption: "The Golgi apparatus, the cell structure that bears his name.", after: 3 },
    { src: "/images/pioneers/camillo-golgi-g1.png", caption: "The neuron, revealed by his black-staining method.", after: 2 },
    { src: "/images/pioneers/camillo-golgi-g2.jpg", caption: "Ramón y Cajal, who shared the Nobel Prize with him.", after: 3 },
  ],
  "galileo-ferraris": [
    { src: "/images/pioneers/galileo-ferraris-work.jpg", caption: "The induction motor, driven by a rotating magnetic field.", after: 2 },
    { src: "/images/pioneers/galileo-ferraris-g1.png", caption: "Alternating current, the system his work helped make practical.", after: 4 },
  ],
  "giuseppe-peano": [
    { src: "/images/pioneers/giuseppe-peano-work.gif", caption: "The Peano curve, a line that fills an entire square.", after: 3 },
    { src: "/images/pioneers/giuseppe-peano-g1.gif", caption: "The Hilbert curve, another space-filling curve in his tradition.", after: 4 },
  ],
  "maria-montessori": [
    { src: "/images/pioneers/maria-montessori-work.jpg", caption: "Montessori learning materials, designed for self-directed discovery.", after: 3 },
    { src: "/images/pioneers/maria-montessori-g1.png", caption: "Children using her teaching devices, the hands-on method she pioneered.", after: 1 },
  ],
  "tullio-levi-civita": [
    { src: "/images/pioneers/tullio-levi-civita-g1.jpg", caption: "Einstein, who relied on Levi-Civita's calculus for general relativity.", after: 3 },
    { src: "/images/pioneers/tullio-levi-civita-g2.jpg", caption: "General relativity, the theory his tensor calculus made possible.", after: 4 },
  ],
  "guglielmo-marconi": [
    { src: "/images/pioneers/guglielmo-marconi-work.jpg", caption: "His wireless telegraphy equipment.", after: 2 },
    { src: "/images/pioneers/guglielmo-marconi-g1.jpg", caption: "The Titanic, whose survivors were rescued thanks to his wireless.", after: 4 },
  ],
  "corradino-dascanio": [
    { src: "/images/pioneers/corradino-dascanio-work.jpg", caption: "The Vespa, the scooter he designed for postwar Italy.", after: 3 },
    { src: "/images/pioneers/corradino-dascanio-g1.jpg", caption: "Roman Holiday, the film that made the Vespa a global icon.", after: 5 },
  ],
  "enzo-ferrari": [
    { src: "/images/pioneers/enzo-ferrari-work.jpg", caption: "The Ferrari 250 GTO, one of the most coveted cars ever made.", after: 3 },
    { src: "/images/pioneers/enzo-ferrari-g1.png", caption: "A Ferrari Formula One car, the racing that was always his true obsession.", after: 2 },
  ],
  "adriano-olivetti": [
    { src: "/images/pioneers/adriano-olivetti-work.jpg", caption: "The Programma 101, an early desktop computer.", after: 3 },
    { src: "/images/pioneers/adriano-olivetti-g1.jpg", caption: "The Lettera 22, a portable typewriter celebrated for its design.", after: 4 },
  ],
  "enrico-fermi": [
    { src: "/images/pioneers/enrico-fermi-work.jpg", caption: "Chicago Pile-1, the first controlled nuclear chain reaction.", after: 3 },
    { src: "/images/pioneers/enrico-fermi-g1.png", caption: "The nuclear chain reaction he first sustained and controlled.", after: 4 },
  ],
  "giulio-natta": [
    { src: "/images/pioneers/giulio-natta-work.png", caption: "The structure of polypropylene, the plastic he helped create.", after: 3 },
    { src: "/images/pioneers/giulio-natta-g1.png", caption: "Everyday plastic objects, made possible by the polymers he learned to control.", after: 4 },
  ],
  "rita-levi-montalcini": [
    { src: "/images/pioneers/rita-levi-montalcini-work.png", caption: "Nerve growth factor, the discovery that won her the Nobel Prize.", after: 3 },
    { src: "/images/pioneers/rita-levi-montalcini-g1.png", caption: "The neuron, whose growth her factor controls.", after: 4 },
  ],
  "margherita-hack": [
    { src: "/images/pioneers/margherita-hack-work.png", caption: "Stellar classification, central to her study of the stars.", after: 2 },
    { src: "/images/pioneers/margherita-hack-g1.jpg", caption: "A large telescope, the kind of instrument she used to study the stars.", after: 3 },
  ],
  "carlo-rubbia": [
    { src: "/images/pioneers/carlo-rubbia-work.png", caption: "The discovery of the W and Z bosons.", after: 3 },
    { src: "/images/pioneers/carlo-rubbia-g1.png", caption: "The Super Proton Synchrotron at CERN, where his team found the W and Z bosons.", after: 1 },
    { src: "/images/pioneers/carlo-rubbia-g2.png", caption: "The Standard Model, confirmed by the particles he found.", after: 4 },
  ],
  "renzo-piano": [
    { src: "/images/pioneers/renzo-piano-work.jpg", caption: "The Shard in London, one of his landmark towers.", after: 3 },
    { src: "/images/pioneers/renzo-piano-g1.png", caption: "The Auditorium Parco della Musica in Rome, one of his civic landmarks.", after: 2 },
    { src: "/images/pioneers/renzo-piano-g2.jpg", caption: "The New York Times Building in Manhattan, one of his towers.", after: 3 },
  ],
  "federico-faggin": [
    { src: "/images/pioneers/federico-faggin-work.jpg", caption: "The Intel 4004, the first commercial microprocessor.", after: 3 },
    { src: "/images/pioneers/federico-faggin-g1.jpg", caption: "The Zilog Z80, the chip from the company he co-founded.", after: 3 },
    { src: "/images/pioneers/federico-faggin-g2.jpg", caption: "The touchscreen, an interface his later company helped pioneer.", after: 4 },
  ],
  "giorgio-parisi": [
    { src: "/images/pioneers/giorgio-parisi-work.png", caption: "Spin glasses, the disordered systems at the heart of his Nobel work.", after: 3 },
    { src: "/images/pioneers/giorgio-parisi-g1.jpg", caption: "Flocking starlings, complex collective behaviour he also studied.", after: 3 },
  ],
};
