update public.project_categories
set is_active = false
where slug = 'virtual-try-on'
  or lower(name) = 'virtual try on';

insert into public.project_categories (slug, name, group_name, sort_order)
values
  ('agency', 'Agency', 'type', 60),
  ('community', 'Community', 'type', 70),
  ('internal-tool', 'Internal Tool', 'type', 80),
  ('plugin', 'Plugin', 'type', 90),
  ('browser-extension', 'Browser Extension', 'type', 100),
  ('web-app', 'Web App', 'type', 110),
  ('mobile-app', 'Mobile App', 'type', 120),
  ('api', 'API', 'type', 130),
  ('data-product', 'Data Product', 'type', 140),
  ('low-code', 'Low-Code', 'technology', 80),
  ('blockchain', 'Blockchain', 'technology', 90),
  ('ar-vr', 'AR/VR', 'technology', 100),
  ('computer-vision', 'Computer Vision', 'technology', 110),
  ('voice-ai', 'Voice AI', 'technology', 120),
  ('cybersecurity', 'Cybersecurity', 'technology', 130),
  ('data-analytics', 'Data & Analytics', 'technology', 140),
  ('devops', 'DevOps', 'technology', 150),
  ('cloud-infrastructure', 'Cloud Infrastructure', 'technology', 160),
  ('payments', 'Payments', 'technology', 170),
  ('robotics', 'Robotics', 'technology', 180),
  ('3d', '3D', 'technology', 190),
  ('gaming', 'Gaming', 'technology', 200),
  ('smb', 'SMB', 'market', 50),
  ('enterprise', 'Enterprise', 'market', 60),
  ('creator-economy', 'Creator Economy', 'market', 70),
  ('local-business', 'Local Business', 'market', 80),
  ('public-sector', 'Public Sector', 'market', 90),
  ('real-estate', 'Real Estate', 'industry', 110),
  ('legal', 'Legal', 'industry', 120),
  ('hr', 'HR', 'industry', 130),
  ('recruiting', 'Recruiting', 'industry', 140),
  ('climate', 'Climate', 'industry', 150),
  ('energy', 'Energy', 'industry', 160),
  ('logistics', 'Logistics', 'industry', 170),
  ('manufacturing', 'Manufacturing', 'industry', 180),
  ('construction', 'Construction', 'industry', 190),
  ('retail', 'Retail', 'industry', 200),
  ('hospitality', 'Hospitality', 'industry', 210),
  ('sports', 'Sports', 'industry', 220),
  ('music', 'Music', 'industry', 230),
  ('events', 'Events', 'industry', 240),
  ('finance', 'Finance', 'industry', 250),
  ('insurance', 'Insurance', 'industry', 260),
  ('creator-tools', 'Creator Tools', 'industry', 270),
  ('social-impact', 'Social Impact', 'industry', 280),
  ('idea', 'Idea', 'stage', 10),
  ('prototype', 'Prototype', 'stage', 20),
  ('mvp', 'MVP', 'stage', 30),
  ('private-beta', 'Private Beta', 'stage', 40),
  ('public-beta', 'Public Beta', 'stage', 50),
  ('live-product', 'Live Product', 'stage', 60),
  ('revenue', 'Revenue', 'stage', 70),
  ('scaling', 'Scaling', 'stage', 80)
on conflict (slug) do update
set
  name = excluded.name,
  group_name = excluded.group_name,
  sort_order = excluded.sort_order,
  is_active = true;
